[package]
name = "wasm"
version = "0.1.0"
authors = ["Julian Viechter <jviechter@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/wasm/lib.rs"

[dependencies]
wasm-bindgen = "0.2.49"
num = "0.2.0"
rayon = "1.2.0"